dast

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -124,3 +124,32 @@ jobs:
             git add java-app/values.yaml
             git diff --cached --quiet || git commit -m "updating helm value"
             git push
+    dast:
+      name: dast test
+      runs-on: ubuntu-latest
+      needs: update-tag
+      steps:
+        - name: app check
+          run: |
+            for i in {1..30}; do
+              if curl -f http://k8s-applicat-javaing-efc46936cd-1242321223.ap-south-1.elb.amazonaws.com/health; then
+                echo "app is running"
+                exit 0
+              fi
+              echo "waiting for app"
+              sleep 10
+            done
+            echo "app failed to run"
+            exit 1
+        - name: OWASP ZAP Baseline Scan
+          uses: zaproxy/action-baseline@v0.14.0
+          with:
+            target: 'http://k8s-applicat-javaing-efc46936cd-1242321223.ap-south-1.elb.amazonaws.com'
+            rules_file_name: '.zap/rules.tsv'   # optional custom rules
+            cmd_options: '-a'                  # '-a' = include alpha passive scan rules
+
+        - name: Upload ZAP Report
+          uses: actions/upload-artifact@v4
+          with:
+            name: zap-scan-report
+            path: report_html.html
